stages:
  - build

libpad:
  stage: build
  tags:
    - eda02
  script:
    - ./configure --debug=true
    - make
  when: manual

uio_pci_dma:
  stage: build
  tags:
    - eda02
  script:
    - cd patches/linux_uio
    - make
  when: manual
