name: CMake

on: [push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        include:
        - cc: gcc
          cxx: g++
        - cc: clang
          cxx: clang++
      fail-fast: false

    env: 
      CC: ${{matrix.cc}}
      CXX: ${{matrix.cxx}}

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -yq libkmod-dev libpci-dev libtool-bin

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: make -j

    - name: Package
      working-directory: ${{runner.workspace}}/build
      run: cpack

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: libpda-${{ matrix.cc }}
        path: ${{runner.workspace}}/build/libpda*.deb
